# Generated by Django 4.0.3 on 2022-04-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoas',
            name='idade',
        ),
        migrations.AddField(
            model_name='pessoas',
            name='email_login',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='sobrenome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
