# Generated by Django 4.0.3 on 2022-04-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_remove_pessoas_idade_pessoas_email_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='senha_login',
            field=models.CharField(default='', max_length=20),
        ),
    ]
